# Generated by Django 3.0.5 on 2020-04-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=60)),
                ('heading', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
